const YOUTUBE_FALLBACK_MESSAGE = 'Este vídeo não tem legenda disponível. Cole o texto manualmente.';

function decodeHtmlEntities(text) {
  return String(text || '')
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, '\'')
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');
}

export function extractYouTubeVideoId(input) {
  const raw = String(input || '').trim();
  if (!raw) return null;

  if (/^[a-zA-Z0-9_-]{11}$/.test(raw)) {
    return raw;
  }

  try {
    const url = new URL(raw);
    const host = url.hostname.replace(/^www\./, '');

    if (host === 'youtu.be') {
      return url.pathname.slice(1, 12) || null;
    }

    if (host === 'youtube.com' || host === 'm.youtube.com') {
      if (url.pathname === '/watch') {
        return url.searchParams.get('v');
      }

      const pathParts = url.pathname.split('/').filter(Boolean);
      if (['embed', 'shorts', 'live'].includes(pathParts[0])) {
        return pathParts[1] || null;
      }
    }
  } catch {
    return null;
  }

  return null;
}

export function parseTranscriptPayload(payload) {
  const text = (payload?.events || [])
    .flatMap(event => event?.segs || [])
    .map(segment => decodeHtmlEntities(segment?.utf8 || ''))
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();

  return text;
}

async function requestTranscript(videoId, { lang, kind, fetchImpl }) {
  const params = new URLSearchParams({
    v: videoId,
    lang,
    fmt: 'json3',
  });

  if (kind) {
    params.set('kind', kind);
  }

  const response = await fetchImpl(`https://www.youtube.com/api/timedtext?${params.toString()}`);
  if (!response.ok) return null;

  const payload = await response.json().catch(() => null);
  const text = parseTranscriptPayload(payload);
  if (!text) return null;

  return { text, language: lang, isAutoGenerated: kind === 'asr' };
}

export async function fetchYouTubeTranscript(input, fetchImpl = fetch) {
  const videoId = extractYouTubeVideoId(input);
  if (!videoId) {
    throw new Error('URL do YouTube inválida. Cole um link de vídeo válido.');
  }

  const attempts = [
    { lang: 'en', kind: '' },
    { lang: 'en-US', kind: '' },
    { lang: 'en-GB', kind: '' },
    { lang: 'en', kind: 'asr' },
    { lang: 'en-US', kind: 'asr' },
    { lang: 'en-GB', kind: 'asr' },
  ];

  for (const attempt of attempts) {
    const transcript = await requestTranscript(videoId, {
      ...attempt,
      fetchImpl,
    }).catch(() => null);

    if (transcript?.text) {
      return {
        videoId,
        text: transcript.text,
        language: transcript.language,
        isAutoGenerated: transcript.isAutoGenerated,
      };
    }
  }

  throw new Error(YOUTUBE_FALLBACK_MESSAGE);
}

export { YOUTUBE_FALLBACK_MESSAGE };
